### ISSUE TITLE
Error in using-the-javascript-library#example

### ISSUE THREAD

**Issue by arminvoid** [RequestNetwork/documentation#3]
I am running into an issue while trying out the following example in the request network JS library guide:  https://docs.request.network/development/using-the-javascript-library#example

```
Unhandled rejection Error: Returned error: Attempting to run transaction which calls a contract function, but recipient address 0xf12b5dd4ead5f743c6baa640b0216200e89b60da is not a contract address
```
This occurs during the execution of
```
const { request } = await requestNetwork.createRequest(
    RequestNetwork.Types.Role.Payee,
    RequestNetwork.Types.Currency.ETH,
    payeesInfo,
    payerInfo,
  );
```

Details: I am running a private blockchain instance using `ganache-cli`.
I understand that:

1. As a step while the above is being executed, the req-net library instantiates the `last-RequestEthereum` contract [here](https://github.com/RequestNetwork/requestNetwork/blob/master/packages/requestNetwork.js/src/servicesContracts/requestEthereum-service.ts#L80)
which picks up the contract from [here](https://github.com/RequestNetwork/requestNetwork/blob/master/packages/requestNetworkArtifacts/artifacts.json#L4)
and finally the address `0xf12b5dd4ead5f743c6baa640b0216200e89b60da` comes from [here](https://github.com/RequestNetwork/requestNetwork/blob/master/packages/requestNetworkArtifacts/RequestEthereum/RequestEthereum-0.0.5-test.json#L600). 

2. Since my version of local blockchain doesn't have the request network smart contract published at that address (nor at any other), I get this error message. 

My question is how do setup my environment so as to be able to develop on top the request network?

**Comment by vrolland** [comment]
Hello atvanguard,

Before running tests you have to deploy the contracts with the command `npm run testdeploy` on a freshly started `ganache-cli`.

It is described [here](https://docs.request.network/development/getting-started#run-the-javascript-library-tests).

Cheers!

**Comment by arminvoid** [comment]
Thanks. Missed this. FYI, `lerna bootstrap` fails on `npm install` node 10. Had to run node 8 to make it work.

**Comment by romaric-juniet** [comment]
We didn't notice it doesn't work on node 10, we'll look into it, thanks for reporting it

**Comment by romaric-juniet** [comment]
Off-topic, but to let you know: I got it fixed by deleting package-lock.json and node_modules/ in  packages/requestNetworkSmartContracts and running `npm i ` again
